#[
  nimr

  Single-file Nim runner: metadata-keyed run cache (absolute path, size, mtime) under a
  human-readable per-script directory, optional temp copy when the source path is not a valid Nim
  module filename, then ``nim c`` and ``execv`` into the compiled binary.
  Concurrent compiles for the same cache entry serialize with a per-binary ``.lock`` file and
  ``flock``; the lock fd is released on exit or ``execv``.

  **POSIX only** (macOS, Linux, and similar). Windows is not supported.

  Usage:
    nimr -h
    nimr run -h
    nimr run <script.nim> [args...]
    nimr cache-clear
    nimr completion zsh

  Zsh completion is generated by argsbarg (``nimr completion zsh`` prints the script to stdout).

  Code Standards:
    - Commands that shell out to non-bundled binaries should check PATH, print install hints, and
      exit non-zero when required commands are missing.
    - Multi-word identifiers:
      - order from general → specific (head-first: main concept, then qualifier)
      - typically topic → optional subtype/format → measured attribute → limit/qualifier
      - e.g. coreProcessExitCodeWait, not waitExitCodeCoreProcess
    - Field names:
      - minimal tokens within the owning type
      - no repeated type/module/domain prefixes unless required for disambiguation
    - module-scope (aka top-level, not-nested) declarations (except imports) must be
      - documented with a doc comment above the declaration
      - sorted alphabetically by identifier (consts, object types, fields inside exported objects,
        vars, then procs)
      - procs: callee before caller when required by the compiler; otherwise alphabetical
    - functions must have a human-readable doc comment, and a blank empty line after the function
    - Function shape:
      - entry-point and orchestration procs read top-down as a short sequence of named steps
      - keep the happy path obvious; move mechanics into helpers with intent-revealing names
    - Helper placement:
      - prefer nested helpers only for tiny logic tightly coupled to one block
      - promote helpers to module scope when nesting makes the caller hard to scan, even if the
        helper currently has one call site
      - shared by ≥2 call sites → smallest common ancestor (often a private proc at module
        scope)
      - must be visible to tests, callbacks, or exports → keep at the level visibility requires
      - recursion between helpers → shared scope as the language requires
    - Parameter shape:
      - if a proc takes more than four primitive or config parameters, prefer an options object
      - if the same cluster of values passes through multiple layers, define a named type for it
    - Branching:
      - materially different pipelines → separate helpers, not interleaved
      - repeated status literals and sentinels → centralized constants (or enums when suitable)
    - POSIX-only (macOS, Linux, etc.); assume POSIX features are available
    - Use argsbarg for CLI features (declare it in ``nimr.nimble`` / your package manager; do not
      vendor argsbarg in this module)
      - default to no shortened flags for newly added options
    - Local dev build for this repo: ``just`` / ``justfile`` (needs ``nim`` + ``nimble`` on PATH)
    - Use line max-width of 100 characters, unless the line is a code block or a URL
    - ``CliCommand.handler`` must be a named proc, not an inline proc literal, and must implement
      the command directly rather than just forwarding to another proc
    - ``cliRun`` entrypoint: first argument must be an inline ``CliSchema(...)`` literal; second
      must be an inline argv expression (e.g. ``commandLineParams()``). Do not use a ``let`` bound
      only to pass schema or argv into ``cliRun`` alone (tests may use variables).
]#

import std/[options, os, osproc, strutils, times]
import argsbarg
import ./languages/[common, go_backend, mojo_backend]
from std/posix import Mode, execv, O_CREAT, O_WRONLY, O_CLOEXEC

proc posixOpen(path: cstring; oflag: cint; mode: Mode): cint {.importc: "open", header: "<fcntl.h>",
    sideEffect.}
proc flock(fd: cint; operation: cint): cint {.importc, header: "<sys/file.h>", sideEffect.}
proc posixClose(fd: cint): cint {.importc: "close", header: "<unistd.h>", sideEffect.}
const LOCK_EX = 2.cint ## advisory exclusive lock (``LOCK_EX`` in ``sys/file.h``)

## Maximum length of the flattened per-script cache directory name (under ``$HOME/.cache/nimr``).
## Longer paths use a readable ``__..__`` truncation in the middle.
const cachePathFlattenMaxLen = 220


## Returns the shebangsy Nim cache directory under ``$HOME/.cache/shebangsy/nim``.
proc cacheDirNimrGet(): string =
  let home = getEnv("HOME")
  if home.len == 0:
    stderr.writeLine "[shebangsy:nim] HOME is not set"
    quit(1)
  home / ".cache" / "shebangsy" / "nim"


## Maps one path segment to a filesystem-safe token (letters, digits, ``.``, ``-``, ``_`` only).
proc coreCacheSegmentEncode(seg: string): string =
  for c in seg:
    case c
    of 'a' .. 'z', 'A' .. 'Z', '0' .. '9', '.', '-', '_':
      result.add c
    else:
      result.add '_'
  while result.contains "__":
    result = result.replace("__", "_")
  result = result.strip(chars = {'_'})
  if result.len == 0:
    result = "_"


## Flattens ``absPath`` into a single directory name: path segments joined by ``__`` (leading
## empty segments from ``/`` are skipped). Long paths truncate with a literal ``__..__`` between
## head and tail.
proc coreCacheAbsPathFlatten(absPath: string): string =
  var norm = absPath.replace("\\", "/")
  var segs: seq[string] = @[]
  if not norm.startsWith("/"):
    norm = "/" & norm
  for part in norm.split('/'):
    if part.len == 0:
      continue
    segs.add coreCacheSegmentEncode(part)
  result = segs.join("__")
  if result.len > cachePathFlattenMaxLen:
    let keepHead = 100
    let keepTail = 80
    if result.len > keepHead + keepTail + 6:
      result = result[0 ..< keepHead] & "__..__" & result[^keepTail .. ^1]


## Per-script cache directory under the nimr cache root for ``scriptAbs``.
proc cacheScriptDirFromAbs(scriptAbs: string): string =
  cacheDirNimrGet() / coreCacheAbsPathFlatten(scriptAbs)


## Deterministic ``mtime`` token for cache leaf filenames (UTC unix seconds only).
proc coreCacheMtimeKey(t: Time): string =
  $toUnix(t)


## Leaf filename stem (no directory): size and mtime only. The per-script cache directory already
## encodes the script path, so the basename is not repeated here.
proc cacheBinaryLeafStem(size: int64; mtime: Time): string =
  "s_" & $size & "_t_" & coreCacheMtimeKey(mtime)


## Absolute path to the cached executable for ``scriptAbs`` with given ``size`` and ``mtime``.
proc cacheBinaryPathFromMeta(scriptAbs: string; size: int64; mtime: Time): string =
  cacheScriptDirFromAbs(scriptAbs) / cacheBinaryLeafStem(size, mtime)


## Path to the compile lock file beside ``binaryPath`` (advisory ``flock`` on this path).
proc cacheLockPathFromBinary(binaryPath: string): string =
  binaryPath & ".lock"


## Opens ``lockPath`` and blocks on an exclusive ``flock``. Returns fd, or ``-1`` if open fails
## (compile proceeds without locking). Caller keeps fd open until exit or ``execv`` (``O_CLOEXEC``).
proc cacheCompileLockAcquire(lockPath: string): cint =
  let fd = posixOpen(cstring(lockPath), cint(O_CREAT or O_WRONLY or O_CLOEXEC), Mode(0o600))
  if fd < 0:
    stderr.writeLine "[nimr] warning: could not open compile lock (continuing without lock): ",
      lockPath, ": ", osErrorMsg(osLastError())
    return -1.cint
  if flock(fd, LOCK_EX) != 0:
    stderr.writeLine "[nimr] warning: flock failed (continuing without lock): ", lockPath, ": ",
      osErrorMsg(osLastError())
    discard posixClose(fd)
    return -1.cint
  fd


## Removes every regular file in ``scriptCacheDir`` except ``keepBinaryPath`` (sibling stale bins).
## Also keeps the active compile lock file beside ``keepBinaryPath`` so a concurrent waiter’s
## ``flock`` stays tied to the same inode.
proc cacheSameScriptStaleRemove(scriptCacheDir, keepBinaryPath: string) =
  let keepLock = cacheLockPathFromBinary(keepBinaryPath)
  if not dirExists(scriptCacheDir):
    return
  for kind, path in walkDir(scriptCacheDir):
    if kind != pcFile:
      continue
    if path == keepBinaryPath or path == keepLock:
      continue
    try:
      removeFile(path)
    except CatchableError:
      discard


## Token for temp build directory name: basename letters/digits only, max 16 chars.
proc coreCacheTmpBuildToken(scriptPath: string): string =
  let (_, base, _) = splitFile(scriptPath)
  var r = ""
  for c in base:
    case c
    of 'a' .. 'z', 'A' .. 'Z', '0' .. '9':
      r.add c
    else:
      discard
  if r.len == 0:
    r = "script"
  if r.len > 16:
    r = r[0 ..< 16]
  let par = extractFilename(parentDir(scriptPath))
  var p = ""
  for c in par:
    case c
    of 'a' .. 'z', 'A' .. 'Z', '0' .. '9':
      p.add c
    else:
      discard
  if p.len > 8:
    p = p[0 ..< 8]
  if p.len > 0:
    result = p & "_" & r
  else:
    result = r


## Removes the Nim backend metadata cache directory.
proc cacheNimClear() =
  let dir = cacheDirNimrGet()
  if not dirExists(dir):
    return
  try:
    removeDir(dir, checkDir = false)
  except CatchableError as e:
    stderr.writeLine "[shebangsy:nim] could not clear cache: ", e.msg
    quit(1)
  stderr.writeLine "[shebangsy:nim] cleared ", dir


## Argsbarg bridge for clearing the Nim cache.
proc nimrCacheClearHandle(ctx: CliContext) =
  discard ctx
  cacheNimClear()


## Clears shebangsy caches; with an optional language argument clears only that backend.
proc shebangsyCacheClearHandle(ctx: CliContext) =
  if ctx.args.len == 0:
    cacheNimClear()
    let goRunner = go_backend.createRunner()
    let goCode = goRunner.clearProc()
    if goCode != 0:
      quit(goCode)
    let mojoRunner = mojo_backend.createRunner()
    let mojoCode = mojoRunner.clearProc()
    if mojoCode != 0:
      quit(mojoCode)
    return

  let language = ctx.args[0].toLowerAscii
  case language
  of "nim":
    cacheNimClear()
  of "go", "golang":
    let code = go_backend.createRunner().clearProc()
    quit(code)
  of "mojo":
    let code = mojo_backend.createRunner().clearProc()
    quit(code)
  else:
    stderr.writeLine "[shebangsy] cache-clear: unknown language: ", language
    quit(1)


## Runs one non-Nim backend using shebang-style args: ``<language> <script> [args...]``.
proc shebangsyLanguageRunHandle(language: string; scriptAndArgs: seq[string]) =
  if scriptAndArgs.len == 0:
    stderr.writeLine "[shebangsy] ", language, ": expected <script> [args...]"
    quit(1)

  let script = scriptAndArgs[0]
  let args =
    if scriptAndArgs.len > 1:
      scriptAndArgs[1 .. ^1]
    else:
      @[]

  let code =
    case language
    of "go", "golang":
      go_backend.createRunner().runProc(script, args)
    of "mojo":
      mojo_backend.createRunner().runProc(script, args)
    else:
      stderr.writeLine "[shebangsy] unsupported language: ", language
      1
  quit(code)


## Writes ``body`` to stdout with a blank line before and after (for ``-h`` / help output).
## Optional ``docAttrsPrefix`` / ``docAttrsSuffix`` wrap ``body`` (e.g. faint ANSI for no-arg help).
proc coreCliHelpStdoutWrite(body: string; docAttrsPrefix = ""; docAttrsSuffix = "") =
  stdout.write '\n'
  stdout.write docAttrsPrefix
  stdout.write body
  stdout.write docAttrsSuffix
  if not body.endsWith('\n'):
    stdout.write '\n'
  stdout.write '\n'


## Runs ``cmd`` with ``args`` in ``workingDir`` and returns the exit code.
proc coreProcessExitCodeWait(cmd: string; args: openArray[string]; workingDir: string): int =
  let p = startProcess(cmd, args = args, workingDir = workingDir, options = {poParentStreams})
  result = waitForExit(p)
  close(p)


## True when ``stem`` is a valid Nim identifier stem.
proc coreIdentStemIsNim(stem: string): bool =
  if stem.len == 0:
    return false
  case stem[0]
  of 'a' .. 'z', 'A' .. 'Z', '_': discard
  of '0' .. '9': return false
  else: return false
  for i in 1 ..< stem.len:
    case stem[i]
    of 'a' .. 'z', 'A' .. 'Z', '0' .. '9', '_': discard
    else: return false
  true


## Reads ``# flags: flag1,flag2`` lines from the first 40 lines of source and returns the
## tokens as a flat list passed to ``nim c``. Multiple directives are merged in order.
proc coreNimFlagsFromSource(content: string): seq[string] =
  result = @[]
  var lineNum = 0
  for line in content.splitLines:
    inc lineNum
    if lineNum > 40:
      break
    if line.startsWith("#!"):
      continue
    let s = line.strip
    const prefix = "# flags:"
    if not s.startsWith(prefix):
      continue
    for part in s[prefix.len .. ^1].split(','):
      let w = part.strip
      if w.len > 0:
        result.add w


## Returns true when the path has a ``.nim`` extension and a basename that is a valid Nim
## module identifier (so the compiler can accept it without a temp rename).
proc coreNimModuleFilenameIsCompatible(path: string): bool =
  let (_, name, ext) = splitFile(path)
  ext == ".nim" and coreIdentStemIsNim(name)


## Reads ``# requires: pkg1,pkg2@ver`` lines from the first 40 lines of source and returns
## the package specs as a flat list. Multiple directives are merged in order.
proc coreNimRequiresFromSource(content: string): seq[string] =
  result = @[]
  var lineNum = 0
  for line in content.splitLines:
    inc lineNum
    if lineNum > 40:
      break
    if line.startsWith("#!"):
      continue
    let s = line.strip
    const prefix = "# requires:"
    if not s.startsWith(prefix):
      continue
    for part in s[prefix.len .. ^1].split(','):
      let w = part.strip
      if w.len > 0:
        result.add w


## Ensures every package spec in ``pkgs`` is installed via ``nimble install -Y`` (output streams
## live when a package is missing) and returns a ``--path:dir`` flag for each resolved location.
## Exits with a message if nimble is not on PATH or any install or path-lookup fails.
proc coreNimRequiresInstallPaths(pkgs: seq[string]): seq[string] =
  result = @[]
  if pkgs.len == 0:
    return
  let nimbleExe = findExe("nimble")
  if nimbleExe.len == 0:
    stderr.writeLine "[nimr] nimble is not on PATH; needed for # requires: ", pkgs.join(", ")
    stderr.writeLine "[nimr] install Nim/Nimble: https://nim-lang.org/install.html"
    quit(1)
  for pkg in pkgs:
    let pkgStem = pkg.split('@')[0].strip
    let (pathPre, pathPreCode) = execCmdEx(nimbleExe & " --silent path " & pkgStem)
    if pathPreCode != 0 or pathPre.strip.len == 0:
      let installCode = coreProcessExitCodeWait(nimbleExe, ["install", "-Y", pkg], "")
      if installCode != 0:
        stderr.writeLine "[nimr] nimble install failed for: ", pkg
        quit(1)
    let (pathOut, pathCode) = execCmdEx(nimbleExe & " --silent path " & pkgStem)
    if pathCode != 0 or pathOut.strip.len == 0:
      stderr.writeLine "[nimr] nimble path failed for: ", pkgStem
      quit(1)
    for line in pathOut.splitLines:
      let w = line.strip
      if w.len > 0:
        result.add "--path:" & w
        break


## Walks up the directory tree from ``walkFromFile`` and returns the first ``pixi.toml`` found,
## or an empty string if none exists.
proc corePixiTomlPathFind(walkFromFile: string): string =
  var dir = parentDir(expandFilename(absolutePath(walkFromFile)))
  while true:
    let manifest = dir / "pixi.toml"
    if fileExists(manifest):
      return manifest
    let parent = parentDir(dir)
    if parent == dir:
      break
    dir = parent
  ""


## Compiles ``nimSource`` to ``binaryPath``. Uses ``pixi run nim c`` when a ``pixi.toml`` is found
## above the script; otherwise invokes ``nim c`` directly.
proc runCompileInvoke(nimSource: string; scriptPathForPixiWalk: string; binaryPath: string;
    nimExtraFlags: openArray[string]): int =
  let workDir = parentDir(nimSource)
  var compileTail = @["c"]
  for f in nimExtraFlags:
    compileTail.add f
  compileTail.add @[
    "--verbosity:0",
    "--hints:off",
    "-o:" & binaryPath,
    nimSource,
  ]
  let manifest = corePixiTomlPathFind(scriptPathForPixiWalk)
  if manifest.len > 0:
    let pixiExe = findExe("pixi")
    if pixiExe.len == 0:
      stderr.writeLine "[nimr] pixi.toml found (", manifest, ") but pixi is not on PATH"
      stderr.writeLine "[nimr] install pixi: https://pixi.sh"
      quit(1)
    let args = @["run", "--manifest-path", manifest, "nim"] & compileTail
    return coreProcessExitCodeWait(pixiExe, args, workDir)
  let nimExe = findExe("nim")
  if nimExe.len == 0:
    stderr.writeLine "[nimr] nim is not on PATH"
    stderr.writeLine "[nimr] install Nim, or add pixi.toml + nim via pixi (https://pixi.sh)"
    quit(1)
  coreProcessExitCodeWait(nimExe, compileTail, workDir)


## Derives the base name for the synthesized ``.nim`` copy when the original filename is not a
## valid Nim module identifier (e.g. ``nimr-neo`` → ``nimr_neo``).
proc runNimStemForNaming(path: string): string =
  let (_, name, ext) = splitFile(path)
  if ext == ".nim":
    name
  else:
    name & ext


## Replaces any character that is not a Nim identifier character with ``_``, collapses runs of
## underscores, strips leading/trailing underscores, and prepends ``_`` if the stem starts with
## a digit.
proc runNimStemSanitize(stem: string): string =
  var r = ""
  for c in stem:
    case c
    of 'a' .. 'z', 'A' .. 'Z', '0' .. '9', '_':
      r.add c
    else:
      r.add '_'
  while r.contains "__":
    r = r.replace("__", "_")
  r = r.strip(chars = {'_'})
  if r.len == 0:
    r = "script"
  if r[0] in '0' .. '9':
    r = "_" & r
  r


## Runs the compiled binary with ``args`` forwarded by replacing this process via ``execv``
## (same exit code as the program). If ``execv`` fails, prints to stderr and quits 126 (POSIX:
## found but could not exec).
proc runBinaryExec(binary: string; args: openArray[string]) =
  flushFile(stdout)
  flushFile(stderr)
  var cmdline = newSeqOfCap[string](1 + args.len)
  cmdline.add binary
  for i in 0 ..< args.len:
    cmdline.add args[i]
  let argvC = allocCStringArray(cmdline)
  discard execv(cstring(binary), argvC)
  stderr.writeLine "[nimr] exec failed: ", binary, ": ", osErrorMsg(osLastError())
  quit(126)


## Handler for the ``run`` subcommand: ``stat``-based cache lookup, compile on miss (installing any
## ``# requires:`` packages after reading the source), sibling purge of stale bins, then run
## the cached binary via ``execv``. A miss takes an exclusive ``flock`` on ``<binary>.lock`` so
## parallel invocations wait and reuse one compile.
proc runNimScriptAndArgsHandle(scriptAndArgs: seq[string]) =

  if scriptAndArgs.len == 0:
    stderr.writeLine "[nimr] run: expected <script> [args...]"
    quit(1)

  let script = scriptAndArgs[0]
  let args =
    if scriptAndArgs.len > 1:
      scriptAndArgs[1 .. ^1]
    else:
      @[]

  let (scriptPath, info) =
    try:
      let sp = expandFilename(absolutePath(script))
      (sp, getFileInfo(sp, followSymlink = true))
    except CatchableError as e:
      stderr.writeLine "[nimr] cannot read script: ", absolutePath(script), ": ", e.msg
      quit(1)

  let size = info.size
  let mtime = info.lastWriteTime
  let scriptCacheDir = cacheScriptDirFromAbs(scriptPath)
  let binaryPath = cacheBinaryPathFromMeta(scriptPath, size, mtime)

  if fileExists(binaryPath):
    runBinaryExec(binaryPath, args)

  createDir(scriptCacheDir)

  let lockPath = cacheLockPathFromBinary(binaryPath)
  discard cacheCompileLockAcquire(lockPath)
  if fileExists(binaryPath):
    runBinaryExec(binaryPath, args)

  let raw = readFile(scriptPath)
  let requirePaths = coreNimRequiresInstallPaths(coreNimRequiresFromSource(raw))
  let allFlags = requirePaths & coreNimFlagsFromSource(raw)

  var nimSource = scriptPath
  var tmpRoot = ""
  if not coreNimModuleFilenameIsCompatible(scriptPath):
    tmpRoot = getTempDir() / ("nimr-build-" & coreCacheTmpBuildToken(scriptPath))
    createDir(tmpRoot)
    let stem = runNimStemSanitize(runNimStemForNaming(scriptPath))
    nimSource = tmpRoot / (stem & ".nim")
    writeFile(nimSource, raw)

  let code = runCompileInvoke(nimSource, scriptPath, binaryPath, allFlags)
  if tmpRoot.len > 0:
    try:
      removeDir(tmpRoot)
    except CatchableError:
      discard
  if code != 0:
    quit(code)

  cacheSameScriptStaleRemove(scriptCacheDir, binaryPath)
  runBinaryExec(binaryPath, args)


## Argsbarg bridge for ``run`` command.
proc nimrRunHandle(ctx: CliContext) =
  runNimScriptAndArgsHandle(ctx.args)


## Prints help for the ``run`` subcommand (stdout).
proc coreRunHelpPrint() =
  coreCliHelpStdoutWrite """
Compile (if needed) and run a Nim source file. Extra tokens are forwarded to the compiled program
unchanged. Nimr replaces itself with the built program via ``execv`` after compile or on a warm
cache hit.

Warm runs use ``stat`` on the script (absolute path, size, modification time) to find a cached
binary under ``$HOME/.cache/nimr`` without reading the whole source. Cache entries live in a
human-readable per-script directory; after a successful rebuild, older binaries for that script are
removed. There is no time-based eviction; use ``nimr cache-clear`` to remove the cache tree.

If two runs start a compile for the same cache entry before the binary exists, the second waits on
``flock`` and then reuses the first compile's output.

Declare Nimble package dependencies in the script with ``# requires:`` (comma-separated
specs); nimr installs them before compiling. Example:

  # requires: neo,argsbarg@1.3.2

Pass extra ``nim c`` flags in the script with ``# flags:`` (comma-separated tokens).
Example:

  # flags: --mm:refc,-d:release

Usage:

nimr run <script.nim> [args...]

""".strip()


## Main entry: language-first shebang dispatch for ``go`` / ``mojo`` / ``nim``, plus legacy
## subcommands for cache management, completion, and explicit Nim ``run``.
when isMainModule:
  let ps = commandLineParams()
  if ps.len >= 1:
    let head = ps[0].toLowerAscii
    case head
    of "go", "golang", "mojo":
      let tail =
        if ps.len > 1:
          ps[1 .. ^1]
        else:
          @[]
      shebangsyLanguageRunHandle(head, tail)
    of "nim":
      let tail =
        if ps.len > 1:
          ps[1 .. ^1]
        else:
          @[]
      runNimScriptAndArgsHandle(tail)
    of "cache-clear":
      if ps.len > 1:
        let language = ps[1].toLowerAscii
        case language
        of "nim":
          cacheNimClear()
          quit(0)
        of "go", "golang":
          quit(go_backend.createRunner().clearProc())
        of "mojo":
          quit(mojo_backend.createRunner().clearProc())
        else:
          stderr.writeLine "[shebangsy] cache-clear: unknown language: ", language
          quit(1)
    else:
      discard

  if ps.len >= 1 and ps[0] == "run":
    if ps.len == 2 and ps[1].len > 0 and ps[1][0] == '-' and ps[1] in ["-h", "--help", "--helpsyntax"]:
      coreRunHelpPrint()
      quit(0)
  cliRun(
    CliSchema(
      commands: @[
        cliLeaf(
          "cache-clear",
          "Remove shebangsy caches (all languages by default).",
          shebangsyCacheClearHandle,
        ),
        cliLeaf(
          "run",
          "Compile and run a Nim script.",
          nimrRunHandle,
          arguments = @[
            cliOptPositional(
              "scriptAndArgs",
              "The Nim file to compile and run, followed by forwarded args.",
              isRepeated = true,
            ),
          ],
        ),
      ],
      description: "Single-file multi-language runner (POSIX): language-first dispatch for nim/go/mojo with metadata-keyed run caches.",
      fallbackCommand: some("run"),
      fallbackMode: cliFallbackWhenMissingOrUnknown,
      name: "shebangsy",
      options: @[],
    ),
    commandLineParams(),
  )
